server:
  port: 28080

grpc:
  server:
    port: 25001
    address: 0.0.0.0
  client:
    kiwi:
      address: static://localhost:15001  # DNS 기반 혹은 정적 주소
      enableKeepAlive: true              # 연결 유지를 위해 주기적으로 ping 전송.
      keepAliveWithoutCalls: true        # 활성 RPC가 없어도 ping 보냄 인프라 정책 확인 필요. 서버/LB 너무 잦으면 연결을 끊을 수 있음
      keepAliveTime: 120s                # ping 주기 (유휴 시간) 마지막 데이터 전송 이후 120초 지나면 ping 전송
      keepAliveTimeout: 30s              # ping 보낸 뒤 응답(ACK)을 기다리는 최대 시간, 초과 시 연결이 비정상이라고 간주
      maxInboundMessageSize: 10485760    # 수신 메시지 최대 크기 (bytes)
      negotiationType: plaintext         # 전송 보안 방식, PLAINTEXT TLS 없이 평문,TLS(인증서 설정 필요)