apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-pg-source-connector
  labels:
    # The strimzi.io/cluster label identifies the KafkaConnect instance
    # in which to create this connector. That KafkaConnect instance
    # must have the strimzi.io/use-connector-resources annotation
    # set to true.
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 2
  config:
    connector.class: io.debezium.connector.postgresql.PostgresConnector
    database.hostname: source-pg-postgresql-hl.database
    database.port: 5432
    database.user: postgres
    database.password: source
    database.dbname: source
    topic.prefix: source
    plugin.name: pgoutput
    slot.name: debezium_slot
    key.converter: io.apicurio.registry.utils.converter.AvroConverter
    key.converter.apicurio.registry.url: http://apicurio-apicurio-registry.kafka-manager/apis/registry/v2
    key.converter.apicurio.registry.auto-register: true
    key.converter.apicurio.registry.find-latest: true
    value.converter: io.apicurio.registry.utils.converter.AvroConverter
    value.converter.apicurio.registry.url: http://apicurio-apicurio-registry.kafka-manager/apis/registry/v2
    value.converter.apicurio.registry.auto-register: true
    value.converter.apicurio.registry.find-latest: true