CREATE TABLE IF NOT EXISTS mst_user (
    id                   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                VARCHAR(255)    NOT NULL UNIQUE,
    nickname             VARCHAR(50)     NOT NULL,
    password             VARCHAR(255)        NULL,
    sign_up_type         VARCHAR(20)     NOT NULL,
    provider             VARCHAR(20)         NULL,
    provider_user_id     VARCHAR(100)        NULL,
    last_login_at        TIMESTAMPTZ         NULL,
    profile_image        VARCHAR(1000)       NULL,
    role                 VARCHAR(50)     NOT NULL,
    login_attempt_count  BIGINT          NOT NULL  DEFAULT 0,

    created_at           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by           BIGINT          NOT NULL DEFAULT 0,
    updated_by           BIGINT          NOT NULL DEFAULT 0,
    is_deleted           BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at           TIMESTAMPTZ         NULL
);

ALTER TABLE mst_user
ADD CONSTRAINT uk_mst_user_provider_provider_user_id
UNIQUE (provider, provider_user_id);

COMMENT ON COLUMN mst_user.created_at IS '데이터가 생성된 시간';
COMMENT ON COLUMN mst_user.updated_at IS '데이터가 수정된 시간';
COMMENT ON COLUMN mst_user.created_by IS '데이터를 생성한 유저 아이디';
COMMENT ON COLUMN mst_user.updated_by IS '데이터를 수정한 유저 아이디';
COMMENT ON COLUMN mst_user.is_deleted IS '소프트 삭제 여부';
COMMENT ON COLUMN mst_user.deleted_at IS '소프트 삭제된 시간';

CREATE TABLE IF NOT EXISTS mst_credit_wallet (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT        NOT NULL UNIQUE,
    balance    BIGINT        NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by BIGINT        NOT NULL DEFAULT 0,
    updated_by BIGINT        NOT NULL DEFAULT 0,
    is_deleted BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ   NULL
);

COMMENT ON COLUMN mst_credit_wallet.created_at IS '데이터가 생성된 시간';
COMMENT ON COLUMN mst_credit_wallet.updated_at IS '데이터가 수정된 시간';
COMMENT ON COLUMN mst_credit_wallet.created_by IS '데이터를 생성한 유저 아이디';
COMMENT ON COLUMN mst_credit_wallet.updated_by IS '데이터를 수정한 유저 아이디';
COMMENT ON COLUMN mst_credit_wallet.is_deleted IS '소프트 삭제 여부';
COMMENT ON COLUMN mst_credit_wallet.deleted_at IS '소프트 삭제된 시간';

CREATE INDEX IF NOT EXISTS idx_mst_credit_wallet_user_id
    ON mst_credit_wallet (user_id);

CREATE TABLE IF NOT EXISTS mst_credit_tx (
    id         UUID          PRIMARY KEY,
    user_id    BIGINT        NOT NULL,
    type       VARCHAR(20)   NOT NULL,
    amount     BIGINT        NOT NULL,
    reason     VARCHAR(100)  NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by BIGINT        NOT NULL DEFAULT 0,
    updated_by BIGINT        NOT NULL DEFAULT 0,
    is_deleted BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ   NULL
);

COMMENT ON COLUMN mst_credit_tx.created_at IS '데이터가 생성된 시간';
COMMENT ON COLUMN mst_credit_tx.updated_at IS '데이터가 수정된 시간';
COMMENT ON COLUMN mst_credit_tx.created_by IS '데이터를 생성한 유저 아이디';
COMMENT ON COLUMN mst_credit_tx.updated_by IS '데이터를 수정한 유저 아이디';
COMMENT ON COLUMN mst_credit_tx.is_deleted IS '소프트 삭제 여부';
COMMENT ON COLUMN mst_credit_tx.deleted_at IS '소프트 삭제된 시간';

CREATE INDEX IF NOT EXISTS idx_mst_credit_tx_user_id_created_at
    ON mst_credit_tx (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS mst_payment_order (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT        NOT NULL,
    provider            VARCHAR(30)   NOT NULL,
    method_ref          VARCHAR(255),
    amount              NUMERIC(19,0) NOT NULL,
    currency            VARCHAR(10)   NOT NULL,
    credits_to_grant    BIGINT        NOT NULL,
    status              VARCHAR(20)   NOT NULL,
    provider_payment_id VARCHAR(255),
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by          BIGINT        NOT NULL DEFAULT 0,
    updated_by          BIGINT        NOT NULL DEFAULT 0,
    is_deleted          BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ   NULL
);

COMMENT ON COLUMN mst_payment_order.created_at IS '데이터가 생성된 시간';
COMMENT ON COLUMN mst_payment_order.updated_at IS '데이터가 수정된 시간';
COMMENT ON COLUMN mst_payment_order.created_by IS '데이터를 생성한 유저 아이디';
COMMENT ON COLUMN mst_payment_order.updated_by IS '데이터를 수정한 유저 아이디';
COMMENT ON COLUMN mst_payment_order.is_deleted IS '소프트 삭제 여부';
COMMENT ON COLUMN mst_payment_order.deleted_at IS '소프트 삭제된 시간';

CREATE INDEX IF NOT EXISTS idx_mst_payment_order_user_id_created_at
    ON mst_payment_order (user_id, created_at DESC);