CREATE TABLE mst_refresh_token (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT           NOT NULL,
  jwt             VARCHAR(1000)    NOT NULL,
  expired_at      TIMESTAMPTZ      NOT NULL,
  created_at      TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  created_by      BIGINT           NOT NULL DEFAULT 0,
  updated_by      BIGINT           NOT NULL DEFAULT 0,
  is_deleted      BOOLEAN          NOT NULL DEFAULT FALSE,
  deleted_at      TIMESTAMPTZ      NULL,

  CONSTRAINT fk_mst_user
  FOREIGN KEY (user_id) REFERENCES mst_user(id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION
);

COMMENT ON TABLE  mst_refresh_token                 IS '리프레시 토큰';
COMMENT ON COLUMN mst_refresh_token.id              IS '식별 인덱스';
COMMENT ON COLUMN mst_refresh_token.user_id         IS 'mst_user.id';
COMMENT ON COLUMN mst_refresh_token.jwt             IS '토큰';
COMMENT ON COLUMN mst_refresh_token.expired_at      IS '만료시간';

COMMENT ON COLUMN mst_refresh_token.created_at      IS '데이터가 생성된 시간';
COMMENT ON COLUMN mst_refresh_token.updated_at      IS '데이터가 수정된 시간';
COMMENT ON COLUMN mst_refresh_token.created_by      IS '데이터를 생성한 유저 아이디';
COMMENT ON COLUMN mst_refresh_token.updated_by      IS '데이터를 수정한 유저 아이디';
COMMENT ON COLUMN mst_refresh_token.is_deleted      IS '소프트 삭제 여부';
COMMENT ON COLUMN mst_refresh_token.deleted_at      IS '소프트 삭제된 시간';