CREATE TABLE his_login_user (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT		   NOT NULL,
  email           VARCHAR(255)     NOT NULL,
  login_at        TIMESTAMPTZ      NOT NULL,
  ip              VARCHAR(50)      NOT NULL,
  agent           VARCHAR(255)     NULL,
  created_at      TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  created_by      BIGINT           NOT NULL DEFAULT 0,
  updated_by      BIGINT           NOT NULL DEFAULT 0,
  is_deleted      BOOLEAN          NOT NULL DEFAULT FALSE,
  deleted_at      TIMESTAMPTZ      NULL,

  CONSTRAINT fk_mst_user
      FOREIGN KEY (user_id) REFERENCES mst_user(id)
      ON UPDATE NO ACTION
      ON DELETE NO ACTION
);

COMMENT ON TABLE  his_login_user                IS '유저 로그인 이력';
COMMENT ON COLUMN his_login_user.id             IS '식별 인덱스';
COMMENT ON COLUMN his_login_user.user_id        IS 'mst_user.id';
COMMENT ON COLUMN his_login_user.email          IS '이메일(로그인 아이디)';
COMMENT ON COLUMN his_login_user.login_at       IS '사용자 로그인 성공 시간';
COMMENT ON COLUMN his_login_user.ip             IS '사용자 IP';
COMMENT ON COLUMN his_login_user.agent          IS '사용자 Agent 정보';

COMMENT ON COLUMN his_login_user.created_at     IS '데이터가 생성된 시간';
COMMENT ON COLUMN his_login_user.updated_at     IS '데이터가 수정된 시간';
COMMENT ON COLUMN his_login_user.created_by     IS '데이터를 생성한 유저 아이디';
COMMENT ON COLUMN his_login_user.updated_by     IS '데이터를 수정한 유저 아이디';
COMMENT ON COLUMN his_login_user.is_deleted     IS '소프트 삭제 여부';
COMMENT ON COLUMN his_login_user.deleted_at     IS '소프트 삭제된 시간';