CREATE TABLE IF NOT EXISTS mst_calligraphy_like (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calligraphy_id UUID          NOT NULL,
    user_id        BIGINT        NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by     BIGINT        NOT NULL DEFAULT 0,
    updated_by     BIGINT        NOT NULL DEFAULT 0,
    is_deleted     BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ   NULL
);

COMMENT ON COLUMN mst_calligraphy_like.id             IS '인덱스';
COMMENT ON COLUMN mst_calligraphy_like.calligraphy_id IS 'mst_calligraphy.id';
COMMENT ON COLUMN mst_calligraphy_like.user_id        IS 'mst_user.id';

COMMENT ON COLUMN mst_calligraphy_like.created_at     IS '데이터가 생성된 시간';
COMMENT ON COLUMN mst_calligraphy_like.updated_at     IS '데이터가 수정된 시간';
COMMENT ON COLUMN mst_calligraphy_like.created_by     IS '데이터를 생성한 유저 아이디';
COMMENT ON COLUMN mst_calligraphy_like.updated_by     IS '데이터를 수정한 유저 아이디';
COMMENT ON COLUMN mst_calligraphy_like.is_deleted     IS '소프트 삭제 여부';
COMMENT ON COLUMN mst_calligraphy_like.deleted_at     IS '소프트 삭제된 시간';

CREATE UNIQUE INDEX IF NOT EXISTS uq_mst_calligraphy_like_calligraphy_user
    ON mst_calligraphy_like (calligraphy_id, user_id);

CREATE INDEX IF NOT EXISTS idx_mst_calligraphy_like_calligraphy
    ON mst_calligraphy_like (calligraphy_id);