CREATE TABLE IF NOT EXISTS mst_calligraphy_feedback (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calligraphy_id UUID          NOT NULL,
    user_id        BIGINT        NOT NULL,
    content        VARCHAR(500)  NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by     BIGINT        NOT NULL DEFAULT 0,
    updated_by     BIGINT        NOT NULL DEFAULT 0,
    is_deleted     BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ   NULL,

    CONSTRAINT fk_mst_calligraphy
    FOREIGN KEY (calligraphy_id) REFERENCES mst_calligraphy(id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);

COMMENT ON COLUMN mst_calligraphy_feedback.calligraphy_id   IS 'mst_calligraphy.id';
COMMENT ON COLUMN mst_calligraphy_feedback.user_id          IS 'mst_user.id';
COMMENT ON COLUMN mst_calligraphy_feedback.content          IS '내용';

COMMENT ON COLUMN mst_calligraphy_feedback.created_at       IS '데이터가 생성된 시간';
COMMENT ON COLUMN mst_calligraphy_feedback.updated_at       IS '데이터가 수정된 시간';
COMMENT ON COLUMN mst_calligraphy_feedback.created_by       IS '데이터를 생성한 유저 아이디';
COMMENT ON COLUMN mst_calligraphy_feedback.updated_by       IS '데이터를 수정한 유저 아이디';
COMMENT ON COLUMN mst_calligraphy_feedback.is_deleted       IS '소프트 삭제 여부';
COMMENT ON COLUMN mst_calligraphy_feedback.deleted_at       IS '소프트 삭제된 시간';