server:
  port: 8181

# chap 05 begin
#greeting-name: Dakota
#greeting-coffee: ${greeting-name} is drinking Cafe Cereza

greeting:
  name: Dakota
  coffee: ${greeting.name} is drinking Cafe Cereza

droid:
  id: BB-8
  description: Small, rolling android. Probably doesn't drink coffee.

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        #        include: env, info, health
        include: '*'
# chap 05 end