version: '3.9'

services:
  postgresql:
    image: postgres:16-alpine
    container_name: lkdcode-postgresql
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: lkdcode
      POSTGRES_PASSWORD: lkdcode
      POSTGRES_DB: lkdcode