server:
  port: 18080

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
    locations: classpath:db/migration

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/lkdcode-flyway
    username: root
    password: lkdcode

  sql:
    init:
      mode: always