CREATE TABLE tb_fruit (
    FRUIT_NUMBER VARCHAR(20) NOT NULL,
    FRUIT_ADDRESS VARCHAR(20) NOT NULL,
    PRICE VARCHAR(20) NOT NULL,
    PRIMARY KEY(FRUIT_NUMBER, FRUIT_ADDRESS)
)

CREATE TABLE tb_store (
    FRUIT_NUMBER VARCHAR(20) NOT NULL,
    FRUIT_ADDRESS VARCHAR(20) NOT NULL,
    STORE_NUMBER VARCHAR(20) NOT NULL,
    STORE_ADDRESS VARCHAR(20) NOT NULL,
    PRICE VARCHAR(20),
    PRIMARY KEY (FRUIT_NUMBER, STORE_NUMBER),
    FOREIGN KEY (FRUIT_NUMBER, FRUIT_ADDRESS) REFERENCES tb_fruit (FRUIT_NUMBER, FRUIT_ADDRESS)
)