DROP TABLE IF EXISTS user_entity;
CREATE TABLE user_entity (
    id BIGINT AUTO_INCREMENT,
    age INT,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS post_entity;
CREATE TABLE post_entity (
    id BIGINT AUTO_INCREMENT,
    user_id BIGINT,
    title VARCHAR(255),
    content VARCHAR(255),
    PRIMARY KEY (id)
);

--DROP TABLE IF EXISTS user_entity;
--create table user_entity (
--    id bigint generated by default as identity,
--    age integer,
--    name varchar(255),
--    primary key (id)
--);
--
--DROP TABLE IF EXISTS post_entity;
--create table post_entity (
--    id bigint generated by default as identity,
--    user_id bigint,
--    title varchar(255),
--    content varchar(255),
--    primary key (id)
--);