server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always

  application:
    name: drawLots

  profiles:
    active: local

logging:
  level:
    #    org.springframework.web: DEBUG

    org.hibernate.SQL: DEBUG  # Hibernate를 통한 SQL 문을 DEBUG 레벨로 로깅합니다.
    org.hibernate.type: TRACE # SQL 쿼리의 매개변수 값을 로깅합니다.
#    root: debug