server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/lkdcode
    username: root
    password: lkdcode

  redis:
    host: localhost
    port: 16379

#  jpa:
#    show-sql: false
#    properties:
#      hibernate:
#        show-sql: false
#        format_sql: false
#        use_sql_comments: false
#        generate_statistics: false
#
#
#logging:
#  level:
#    org.hibernate: warn
#    org.hibernate.SQL: off
#    org.hibernate.type.descriptor.sql: off
#    org.hibernate.orm.jdbc.bind: off
#    org.hibernate.orm.jdbc.extract: off
#    # (선택) JDBC 템플릿이나 다른 SQL 로거도 차단
#    org.springframework.jdbc.core: off
#    sql: off