KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_apple_producer="apple-producer-secret"
    user_apple_consumer="apple-consumer-secret"
    user_banana_producer="banana-producer-secret"
    user_banana_consumer="banana-consumer-secret";
};